from H1 import *
hRead = open("F:\\test\\1.3\\14.txt", "r")
hWrite = open("F:\\test\\1.3\\ans14.txt","w")
n=int(hRead.readline())
e=float(hRead.readline())
A= [0]*n
for i in range(n):
    A[i]=list(map(int, hRead.readline().split()))
S=list(map(int, hRead.readline().split()))
ans=chekIt(A,n)
writeMat(A,hWrite)
hWrite.write("это A\n")
writeV(S,hWrite)
hWrite.write("это S\n")
hWrite.write(str(e))
hWrite.write("\nэто e\n")
x1=metIt(A,S,n,e,hWrite,ans)
writeV(x1,hWrite)
hWrite.write("это ответ для метода итераций\n")
x2=metZeid(A,S,n,e,hWrite,ans)
writeV(x2,hWrite)
hWrite.write("это ответ для метода зейделя\n")
hRead.close()
hWrite.close()
